rule_name="www.01xs.com"
[metadata]
#书名的html属性表达式
name_regexp = { selector = "meta[property=\"og:novel:book_name\"]", attr = "content" }

#作者的html属性表达式
author_regexp = { selector = "meta[property=\"og:novel:author\"]" , attr = "content"}
#简介的html属性表达式
intro_regexp = { selector = "meta[property=\"og:description\"]" , attr = "content"}
#小说分类的html表达式
category_regexp = {selector = "meta[property=\"og:novel:category\"]",attr = "content"}
#小说封面的属性表达式
cover_regexp = { selector = "meta[property=\"og:image\"]", attr = "content"}


[chapter]
#是否开启分页
is_pagination = false
#如果存在分页，获取分页的html表达式
pagination_regexp = []
#小说章节列表html属性表达式
catalog_regexp = [{ selector = ".main > .chapterlist", index = 1}, { selector = "ul > li > a", index = -1}]

[content]
#是否开启分页
is_pagination = false
#如果存在分页，获取分页的html表达式
pagination_regexp = []
content_regexp = [{selector = "#content", index = 0}]
filter_text = []
filter_html = ["div","p","script"]